name: Makefile CI

on:
  [push, workflow_dispatch]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Download dependencies
      run: sudo apt-get update && sudo apt-get install -y tzdata && sudo apt-get install -y build-essential libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev

    - name: configure
      run: ./configure

        #- name: Add missing
        #run: automake --add-missing

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck

    - name: Create artifacts
      run:
        tar cvf barkout-1.2.tar.gz configure configure.ac AUTHORS COPYING INSTALL NEWS  Fonts/ Levels/ Sounds/ src/ Sprites/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with: 
        name: barkout-1.2.tar.gz
        path: barkout-1.2.tar.gz
