name: Windows Package

on: [workflow_dispatch]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Libraries
        run:
          wget -nv https://github.com/libsdl-org/SDL/releases/download/release-2.28.5/SDL2-devel-2.28.5-mingw.tar.gz
          
          wget -nv https://github.com/libsdl-org/SDL_image/releases/download/release-2.8.0/SDL2_image-devel-2.8.0-mingw.tar.gz
          
          wget -nv https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.6.3-mingw.tar.gz
          
          wget -nv https://github.com/libsdl-org/SDL_ttf/releases/download/release-2.20.2/SDL2_ttf-devel-2.20.2-mingw.tar.gz
      - name: Unpack Libraries
        run:
          tar xvf SDL2-devel-2.28.5-mingw.tar.gz
          
          tar xvf SDL2_image-devel-2.8.0-mingw.tar.gz
          
          tar xvf SDL2_mixer-devel-2.6.3-mingw.tar.gz
          
          tar xvf SDL2_ttf-devel-2.20.2-mingw.tar.gz
          
          cp -r SDL2-2.28.5/x86_64-w64-mingw32 .
          
          cp -r SDL2_image-2.8.0/x86_64-w64-mingw32 .
          
          cp -r SDL2_mixer-2.6.3/x86_64-w64-mingw32 .
          
          cp -r SDL2_ttf-2.20.2/x86_64-w64-mingw32 .
                    
          ./x86_64-w64-mingw32/bin/sdl2-config --cflags --libs
      - name: Build tools
        run:
          sudo apt-get update && sudo apt-get install -y tzdata build-essential mingw-w64
      - name: Build game
        working-directory: ./src
        run:
          x86_64-w64-mingw32-gcc-win32 `../x86_64-w64-mingw32/bin/sdl2-config --cflags --libs` -I ../x86_64-w64-mingw32/include -o barkout.exe -g -O2 resourcefactory.c resources.c bounds.c config.c levels.c menu.c save.c scores.c ball.c bonus.c cat.c bat.c text.c intro.c arena.c vector.c barkanoid.c -lm -lSDL2 -lSDL2_mixer -lSDL2_image -lSDL2_ttf
      - name: Copy files
        run:
          mkdir Barkout && cp -r src/barkout.exe Sprites/* Fonts/* Sounds/* Levels/* x86_64-w64-mingw32/bin/*.dll Barkout
      - name: Download NSIS
        run:
          sudo apt-get install -y nsis
      - name: Build installer
        run:
          makensis -VERSION
